AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation to deploy s3 bucket for Lambda packages

Parameters:
  EnvironmentName:
    Description: The environment the template is being run in. Used for naming resources
    Type: String
    AllowedValues:
      - nonprod
      - preprod
      - prod
    Default: nonprod
  BucketName:
    Description: Name of bucket to store Lambda packages
    Type: String
    Default: Upload-picture-bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

